<!DOCTYPE html>
<html class="h-100" lang="br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Usuários</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    
</head>
<body>
    <div class="container-fluid">
        <div class="container mt-5" style="background-color: rgba(0,0,0,0.1);">
            <h3>Usuários</h3>
            <div>
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col">Id:</th>
                        <th scope="col">Nome:</th>
                        <th scope="col">Email:</th>
                        <th scope="col">Senha:</th>
                        <th scope="col">Tipo Usuário:</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($lista as $item) {
                    	echo '<tr>';
                            echo '<th scope="row">'.$lista['Id'].'</th>';
                            echo '<td>'.$lista['Nome'].'</td>';
                            echo '<td>'.$lista['Email'].'</td>';
                            echo '<td>'.$lista['Senha'].'</td>';
                            if ($lista['Id_Tipo_Usuario'] = 1){
                            	echo '<td>Admin</td>';
                            }elseif ($lista['Id_Tipo_Usuario'] = 0) {
                            	echo '<td>Comum</td>';
                            }else{
                            	echo '<td>Indefinido</td>';
                            }
                            echo '<td><a href="/del='.$lista['Id'].'">delete</a></td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    
</body>
</html>