<!DOCTYPE html>
<html class="h-100" lang="br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Usuários</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    
</head>
<body>
    <div class="container-fluid">
        <div class="container mt-5" style="background-color: rgba(0,0,0,0.1);">
            <h3>Usuários</h3>
            <div>
            <table class="table table-dark">
                <thead>
                    <form action="./" method="post">
                        <div class="row">
                            <input type="text" name="nome" class="col-6 ml-3 mb-3 form-control" placeholder="Digite um nome para pesquisa">
                            <input type="submit" class="btn btn-dark ml-2 mb-3" value="Pesquisar">
                        </div>
                    </form>
                    <tr>
                        <th scope="col">Id:</th>
                        <th scope="col">Nome:</th>
                        <th scope="col">Email:</th>
                        <th scope="col">Senha:</th>
                        <th scope="col">Tipo Usuário:</th>
                        <th scope="col">
                            <form action="./add-user" method="get">
                                <div class="row">
                                    <input type="submit" class="btn btn-sm btn-light ml-2 w-75" value="Novo">
                                </div>
                            </form>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        if (count($lista) > 0){
                            foreach ($lista as $item): 
                    			echo '<tr >';
	                                echo '<th scope="row">'.$item['Id'].'</th>';
	                                echo '<td>'.$item['Nome'].'</td>';
	                                echo '<td>'.$item['Email'].'</td>';
	                                echo '<td>'.$item['Senha'].'</td>';
	                                echo '<td>'.$item['Descricao'].'</td>';
	                                echo '<td><a href="./edt/'.$item['Id'].'">Editar</a> <a href="./del/'.$item['Id'].'">Excluir</a></td>';
                   				echo '</tr>';
                            endforeach;
                        }
                        else{
                            echo '<th scope="row">-</th>';
                            echo '<td>Nenhum Usuário encontrado</td>';
                        }
                    ?>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    
</body>
</html>